# Generated by Django 4.1.1 on 2022-10-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название комнаты', max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания комнаты')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления комнаты')),
            ],
        ),
    ]
